name: Test

on:
  workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: andrewdyer/github-workflows/.github/actions/prepare-node@main

      - name: Run tests
        run: npm test
        